name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user --no-cache-dir -r requirements.txt

    - name: Run tests with coverage
      run: |
         ~/.local/bin/pytest --cov=proj --cov-report=xml --cov-report=term
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
    - name: Annotate PR with coverage summary
      if: github.event_name == 'pull_request'
      uses: dorny/test-reporter@v1
      with:
        name: Coverage Report
        path: coverage.xml
        reporter: junit

# If you don't want to use coverage, you can use the following configuration 
#    - name: Run tests
#      run: |
#         ~/.local/bin/pytest